name: login
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_modular: ^4.4.0
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.3+2
  dartz: ^0.10.1
  equatable: ^2.0.3
  connectivity_plus: ^2.2.0
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  mobx_codegen:
  modular_codegen: ^3.0.3
  build_runner:
  json_serializable: ^6.1.4
  effective_dart: ^1.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/